name: Deploy to Railway (development env)

on:
  pull_request:
    types:
    - open
    branches:
    - master


jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Codeball
      uses: sturdy-dev/codeball-action@v2
      with:
        # For all configuration options see https://github.com/sturdy-dev/codeball-action/blob/v2/action.yml
        approvePullRequests: "true"
        labelPullRequestsWhenApproved: "true"
        labelPullRequestsWhenReviewNeeded: "false"
        failJobsWhenReviewNeeded: "false"