name: Deploy to Railway (development env)

on:
  push:
    branches: [develop]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        content: "TEST NOTIFICATION"